{{$secretsLocation := env "SECRETS_LOCATION"}}
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-key
  namespace: {{ env "NAMESPACE" }}
type: Opaque
data:
  gkey.json: "{{ with secret (printf "secret/community_squad/%s/gcloud/community-datastore-credentials" $secretsLocation) }}{{ .Data.value | base64Encode }}{{ end }}"