---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ env "APP_NAME" }}-hpa
  namespace: {{ env "NAMESPACE" }}
  labels:
    app: {{ env "APP_NAME" }}
    release: {{ env "KD_RELEASE_NAME" }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ env "KD_RELEASE_NAME" }}
  minReplicas: {{ env "MIN_REPLICA" }}
  maxReplicas: {{ env "MAX_REPLICA" }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ env "CPU_TARGET" }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ env "MEMORY_TARGET" }}
